Repository desihub/desisim, pull requests merged in 2018-12, with the labels that each got.

#455 fix error in size of Z_noFOG
  py/desisim/scripts/quickquasars.py
Labels: bug

#457 Fix quickquasars targetid truth
  py/desisim/scripts/quickquasars.py
Labels: bug, enhancement

#453 precompute colors for star and galaxy templates
  bin/precompute-template-colors
  doc/changes.rst
  py/desisim/io.py
  py/desisim/templates.py
Labels: enhancement
